services:
  dequity-blockchain:
    image: gitlab.itglobal.com:5050/dequity/blockchain/dequity-blockchain:latest
    container_name: dev-dequity-blockchain
    restart: always
    env_file:
      - .env
    expose:
      - "${PORT}"

  dequity-blockchain-postgres:
    image: postgres:14-alpine
    container_name: dev-dequity-blockchain-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "${POSTGRES_PORT}"
    command: postgres -c 'max_connections=200'

volumes:
  postgres_data:

networks:
  default:
    name: dequity-net
    external: true
